fix: coloured error messages are now displayed correctly [4]

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -11,11 +11,11 @@ commit_msg_file=$1
 commit_message=$(cat "$commit_msg_file")
 
 if [ -z "$commit_message" ]; then
-    echo "\n${RED}ERROR: commit message cannot be empty.${NC}"
-    echo "\n${GREEN}Expected format: \"fix/feat: commit message [issue_number]\"${NC}\n"
-    echo "\n${CYAN}Examples:${NC}" >&2
-    echo "fix: correct bug in authentication flow [123]" >&2
-    echo "feat: add new user profile page [456]" >&2
+    echo -e "\n${RED}ERROR: commit message cannot be empty.${NC}"
+    echo -e "\n${GREEN}Expected format: \"fix/feat: commit message [issue_number]\"${NC}\n"
+    echo -e "\n${CYAN}Examples:${NC}" >&2
+    echo -e "fix: correct bug in authentication flow [123]" >&2
+    echo -e "feat: add new user profile page [456]" >&2
     exit 1
 fi
 
@@ -23,12 +23,12 @@ fi
 commit_regex="^(fix|feat): [a-zA-Z0-9 ,'-]+ \[[0-9]+\]$"
 
 if ! echo "$commit_message" | grep -Eq "$commit_regex"; then
-    echo "\n${RED}ERROR: invalid commit message.${NC}"
-    echo "\n${GREEN}Expected format: \"fix/feat: commit message [issue_number]\"${NC}\n"
-    echo "\nCurrent message: ${RED}$commit_message${NC}" >&2
-    echo "\n${CYAN}Examples:${NC}" >&2
-    echo "fix: correct bug in authentication flow [123]" >&2
-    echo "feat: add new user profile page [456]" >&2
+    echo -e "\n${RED}ERROR: invalid commit message.${NC}"
+    echo -e "\n${GREEN}Expected format: \"fix/feat: commit message [issue_number]\"${NC}\n"
+    echo -e "\nCurrent message: ${RED}$commit_message${NC}" >&2
+    echo -e "\n${CYAN}Examples:${NC}" >&2
+    echo -e "fix: correct bug in authentication flow [123]" >&2
+    echo -e "feat: add new user profile page [456]" >&2
     exit 1
 fi
 
@@ -41,8 +41,8 @@ echo "$commit_message"  # This will show if there are hidden spaces or special c
 commit_message_lower=$(echo "$commit_message" | tr '[:upper:]' '[:lower:]')
 
 if [ "$commit_message" != "$commit_message_lower" ]; then
-    echo "\n${RED}ERROR: commit message must be lowercase only.${NC}" >&2
-    echo "\nCurrent message: ${RED}$commit_message${NC}" >&2
-    echo "\nMake sure all the letters in your commit message are lowercase.\n" >&2
+    echo -e "\n${RED}ERROR: commit message must be lowercase only.${NC}" >&2
+    echo -e "\nCurrent message: ${RED}$commit_message${NC}" >&2
+    echo -e "\nMake sure all the letters in your commit message are lowercase.\n" >&2
     exit 1
 fi
